eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clients
          uri: http://localhost:8090
          predicates:
            - Path=/api/client/**
        - id: vehicles
          uri: http://localhost:9090
          predicates:
            - Path=/api/vehicle/**

  allowed-urls: http://localhost:4200, http://localhost:3000
